spring:
  h2:
    console:
      path: /h2-console
      enabled: false
  datasource:
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/h2db/hero
    platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info
bot:
  username:
  token: